### ISSUE TITLE
Trying to install but failed in libexpat

### ISSUE THREAD

**Issue by boedyirh** [viest/php-ext-xlsxread#1]
I am interested with this extension (xlsx read) , been trying the xlsx writer....it is super fast!!!

I am trying to install the xlsxread extension.
But failed when running 
./configure --with-php-config=/urs/bin/php-config  
![libexpat](https://user-images.githubusercontent.com/10396931/52273026-29c4f280-297b-11e9-8a21-6c2567142ccf.JPG)

I am using debian stretch 9. x64

apt-get install libzip-dev --->already the newest version
apt-get install expat --> already the newest version
apt-get install libexpat1 --> already the newest version (2.2.0)
apt-get install libexpat1-dev -> already the newest

still cannot resolve the dependency

**Comment by viest** [comment]
You can view the CI script `before_script ` 

https://github.com/viest/php-ext-xlsxread/blob/master/.travis.yml

**Comment by boedyirh** [comment]
Thanks. It does work !!
