### ISSUE TITLE
xlsxread windows dll

### ISSUE THREAD

**Issue by boedyirh** [viest/php-ext-xlsxread#2]
Thanks for the extension.
I am able to run it on linux debian.
How to run the phpextension in windows.
I can find the repository for xlswriter  
https://windows.php.net/downloads/pecl/releases/xlswriter/
but still cannot find the dll for xlsx reader.

Thanks

**Comment by viest** [comment]
@boedyirh  
New document: https://xlswriter-docs.viest.me/ , but reader not support windows.
