### ISSUE TITLE
希望继续完善

### ISSUE THREAD

**Issue by vioulo** [viest/php-ext-xlsxread#3]
希望作者加油继续完善这个功能，用处很大的；
我使用的 laravel-excel 读取五列文件，行数还不到 50，但内存占用超出了 128M :dog:

**Comment by viest** [comment]
从未停下脚步

**Comment by vioulo** [comment]
今天测试遇到了一个问题，在读取 xlsx 文件时候会多读取几行；还有奇怪的现象，扩展以及 laravel-excel 读取一部分文件，竟然读取了 1万多列；这样的情况是不是文件中单元格样式引起的？
比如，第一种情况，一块样式统一但区别于空白区域的内容下面几行删掉了；第二种情况，就是包含内容区域，所有的区域样式都是统一的，所以程序获取的内容达到了 1万多列 ~

**Comment by viest** [comment]
默认是忽略空单元格

**Comment by vioulo** [comment]
> 默认是忽略空单元格

:sob: 我这里有两份文件，不知道你有没有时间测试下。一份文件是读取到了很多空列（和 laravel-excel 类似），一份文件是读取不到数据。
还有，我想了解下，如果要有能力看懂扩展的源码，要学那些东西 :crying_cat_face:

**Comment by viest** [comment]
请将你的扣扣或微信通过邮件的方式发送给我一下

vioulo <notifications@github.com> 于 2019年8月8日周四 下午5:48写道：

**Comment by vioulo** [comment]
我微信是 `sleepwcat`，给你发邮件似乎被拒收

**Comment by viest** [comment]
@vioulo  

请阅读新文档 https://xlswriter-docs.viest.me/
